appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: k9Kjf9gqiXIqX7WEab/ChdrwKBn8etDVEGab+urpAZ3hYzRv8tp/2p28h5DogDpcX4wjN1qg0Ifr5JSp/6jIqzIbcgATYo7prsaXoKRnWb6NewYe9qP/x4qwV9d4+VtqTxXEsYjd16jEDi9XgT/1vSySNO2adkn6FJKzAhogmvgit2lNa/eDhXtcOPRSG3MRSUW5qcbl6u9AKIn/R/I8KO//DawVaZDHQeOtif5PMB8cSGELzSEYsVIi9diPqnhj7I3UOnntZLKNX22XPYIR5w2v3E3ba0BUmdDPldZRVZB87MtFD6vkvneibhHw+1BaGz3g75F9LV0lTmk3wI++rtXsfxRhbunJbAaqO6MGI80u9FgEozSBbLNmsHaWk4RlYsorShB66TjpdH9DUE27QACzKDqrqx/br9pE+TWShU3kdQHyOGxaIVSBMEnpHzYAgDOfrCKdtFGvRgR2UfLnCvdqxQvAhy5nO9IM7mMlGWQ8iA64v1LCfUIKs6wiTMaO3yXT2D7OEjoyCh+pHJhyu+Q2Sqm2upckB6dNt4a0ehOv22EFxNgh8a0fcAVK7UFX0FlENCULmdHvSQFk1fcPWqFspjFP19Mi9ImsZyapSCwDZStB2I9uJG2KdzpgypnVR8iA79b4CyNHTB22N7wOH81WWkvoqv4FxQycARHRUCY=}
provider:
  win: azure
conda_forge_output_validation: true
